import type { Theme, Product } from '@/types/types'

export const THEMES: Record<string, Theme> = {
  minimal: {
    id: 'minimal',
    name: 'Minimal Clean',
    '--bg': '#ffffff',
    '--surface': '#ffffff',
    '--surface-alt': '#f8f8f8',
    '--border-color': '#ebebeb',
    '--radius': '8px',
    '--accent': '#4a6cf7',
    '--accent-rgb': '74,108,247',
    '--text': '#1a1a1a',
    '--text-sub': '#888888',
    '--card-shadow': 'none',
    '--card-shadow-hover': '0 4px 20px rgba(0,0,0,0.09)',
    '--btn-radius': '6px',
    '--store-cols': '3',
  },
  organic: {
    id: 'organic',
    name: 'Soft Organic',
    '--bg': '#fafaf8',
    '--surface': '#ffffff',
    '--surface-alt': '#f3f0eb',
    '--border-color': '#ede8e0',
    '--radius': '16px',
    '--accent': '#5b8c5a',
    '--accent-rgb': '91,140,90',
    '--text': '#2c2c2c',
    '--text-sub': '#9a9088',
    '--card-shadow': '0 4px 16px rgba(0,0,0,0.07)',
    '--card-shadow-hover': '0 10px 32px rgba(0,0,0,0.13)',
    '--btn-radius': '99px',
    '--store-cols': '3',
  },
  editorial: {
    id: 'editorial',
    name: 'Bold Editorial',
    '--bg': '#f2f2f0',
    '--surface': '#ffffff',
    '--surface-alt': '#e8e8e4',
    '--border-color': '#ddddd8',
    '--radius': '4px',
    '--accent': '#e85d47',
    '--accent-rgb': '232,93,71',
    '--text': '#111111',
    '--text-sub': '#777777',
    '--card-shadow': '0 1px 4px rgba(0,0,0,0.08)',
    '--card-shadow-hover': '0 8px 24px rgba(0,0,0,0.15)',
    '--btn-radius': '4px',
    '--store-cols': '2',
  },
  darkminimal: {
    id: 'darkminimal',
    name: 'Dark Minimal',
    '--bg': '#0f0f12',
    '--surface': '#1a1a22',
    '--surface-alt': '#222230',
    '--border-color': '#2e2e3e',
    '--radius': '8px',
    '--accent': '#7b8fff',
    '--accent-rgb': '123,143,255',
    '--text': '#f0f0f8',
    '--text-sub': '#6a6a88',
    '--card-shadow': '0 2px 12px rgba(0,0,0,0.4)',
    '--card-shadow-hover': '0 8px 32px rgba(0,0,0,0.6)',
    '--btn-radius': '6px',
    '--store-cols': '3',
  },
  darkwarm: {
    id: 'darkwarm',
    name: 'Dark Warm',
    '--bg': '#16130f',
    '--surface': '#211d18',
    '--surface-alt': '#2a2520',
    '--border-color': '#3a3328',
    '--radius': '12px',
    '--accent': '#e8a84a',
    '--accent-rgb': '232,168,74',
    '--text': '#f5efe6',
    '--text-sub': '#7a6e60',
    '--card-shadow': '0 2px 14px rgba(0,0,0,0.45)',
    '--card-shadow-hover': '0 10px 36px rgba(0,0,0,0.65)',
    '--btn-radius': '10px',
    '--store-cols': '3',
  },
}

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Керамическая кружка ручной работы',
    description:
      'Изящная кружка из белой глины с матовым покрытием. Каждое изделие уникально — форма вытянута вручную на гончарном круге. Идеальна для утреннего кофе или ароматного чая.',
    price: 2400,
    salePrice: 1800,
    tags: ['керамика', 'кухня', 'handmade'],
    photo: null,
  },
  {
    id: 2,
    name: 'Льняная сумка-шопер',
    description:
      'Вместительная сумка из натурального льна. Плотный материал не мнётся и долго служит. Удобные короткие ручки и длинный ремень в комплекте.',
    price: 1800,
    salePrice: null,
    tags: ['сумки', 'лён', 'eco'],
    photo: null,
  },
  {
    id: 3,
    name: 'Соевая свеча с лавандой',
    description:
      'Ароматическая свеча из натурального соевого воска с эфирным маслом лаванды. Горит до 40 часов, не коптит. В стеклянном стакане с деревянным фитилём.',
    price: 950,
    salePrice: 750,
    tags: ['свечи', 'дом', 'аромат'],
    photo: null,
  },
  {
    id: 4,
    name: 'Вязаная шапка бини',
    description:
      'Мягкая шапка из 100% мериносовой шерсти. Тёплая и лёгкая. Доступна в пяти цветах. Универсальный размер, подходит взрослым.',
    price: 1600,
    salePrice: null,
    tags: ['аксессуары', 'зима', 'шерсть'],
    photo: null,
  },
  {
    id: 5,
    name: 'Набор сушёных трав для чая',
    description:
      'Травяной сбор: ромашка, мята, иван-чай и липовый цвет. Собраны вручную в экологически чистых угодьях Алтая. Без добавок и ароматизаторов.',
    price: 680,
    salePrice: null,
    tags: ['wellness', 'чай', 'травы'],
    photo: null,
  },
  {
    id: 6,
    name: 'Хлопковые салфетки (4 шт)',
    description:
      'Мягкие многоразовые салфетки из органического хлопка. Стираются при 60°C. Экологичная замена бумажным — один набор служит годами.',
    price: 1200,
    salePrice: 960,
    tags: ['кухня', 'eco', 'хлопок'],
    photo: null,
  },
  {
    id: 7,
    name: 'Деревянная ложка ручной работы',
    description:
      'Ложка из карельской берёзы, покрытая льняным маслом. Отличный подарок и практичная вещь на каждый день. Не впитывает запахи.',
    price: 890,
    salePrice: null,
    tags: ['кухня', 'дерево', 'handmade'],
    photo: null,
  },
  {
    id: 8,
    name: 'Мыло с лавандой и овсом',
    description:
      'Натуральное мыло холодного омыления с лавандой и овсом. Питает и смягчает кожу. Подходит для ежедневного использования.',
    price: 450,
    salePrice: null,
    tags: ['wellness', 'красота', 'натуральное'],
    photo: null,
  },
]
